# 重负载场景 - 测试拥塞处理
network:
  constellation: "globalstar"
  ground_stations: 12
  satellite_bandwidth: 8.0    # 减少带宽制造拥塞
  ground_bandwidth: 4.0

algorithm:
  K: 2
  r3: 60                      # 增大权重上界
  Ne_th: 3                    # 提高阈值

traffic:
  total_gbps: 10.0            # 高流量
  duration: 200.0
  elephant_ratio: 0.4