# 性能测试场景 - Iridium星座
network:
  constellation: "iridium"
  ground_stations: 15

algorithm:
  K: 2
  r3: 50                      # 论文最优值

traffic:
  total_gbps: 8.0
  duration: 180.0
  elephant_ratio: 0.3