# 高负载压力测试场景
simulation:
  name: "LDMR High Load Stress Test"
  description: "高负载压力测试 - 验证LDMR在拥塞环境下的优势"

network:
  constellation: "globalstar"
  ground_stations: 15          # 增加地面站数量
  satellite_bandwidth: 6.0     # 减少链路带宽模拟拥塞
  ground_bandwidth: 3.0

algorithm:
  name: "LDMR"
  config:
    K: 2
    r1: 1
    r2: 10
    r3: 50
    Ne_th: 2
    enable_statistics: true

traffic:
  total_gbps: 18.0            # 大幅增加流量负载
  duration: 300.0             # 延长测试时间
  elephant_ratio: 0.4         # 增加大象流比例
  elephant_threshold: 80.0    # 提高大象流阈值

output:
  results_dir: "results/stress_test"
  save_detailed_paths: false
  log_level: "INFO"
