# LDMR算法默认配置文件
# 此文件包含所有标准仿真参数

simulation:
  name: "LDMR Standard Simulation"
  version: "1.0"
  description: "标准LDMR链路不相交多路径路由算法仿真"

# 网络拓扑配置
network:
  constellation: "globalstar"  # 星座类型: globalstar, iridium
  ground_stations: 10          # 地面站数量
  satellite_bandwidth: 10.0    # 卫星链路带宽 (Gbps)
  ground_bandwidth: 5.0        # 地面链路带宽 (Gbps)

# LDMR算法配置
algorithm:
  name: "LDMR"
  config:
    K: 2                    # 每个节点对的路径数量
    r1: 1                   # 权重下界1
    r2: 10                  # 权重下界2
    r3: 50                  # 权重上界
    Ne_th: 2                # 链路利用频次阈值
    max_iterations: 10      # 最大迭代次数
    enable_statistics: true # 启用详细统计

# 流量配置
traffic:
  total_gbps: 6.0           # 总流量 (Gbps)
  duration: 180.0           # 仿真时长 (秒)
  elephant_ratio: 0.3       # 大象流比例
  elephant_threshold: 50.0  # 大象流阈值 (Mbps)

# 流量生成参数
traffic_generation:
  alpha: 0.5                # 流量密度指数
  beta: 2.0                 # 距离衰减指数
  pareto_shape_on: 1.5      # on-time形状参数
  pareto_scale_on: 500      # on-time尺度参数 (ms)
  pareto_shape_off: 1.5     # off-time形状参数
  pareto_scale_off: 1000    # off-time尺度参数 (ms)

# 输出配置
output:
  results_dir: "results"           # 结果保存目录
  log_dir: "logs"                  # 日志保存目录
  auto_timestamp: true             # 自动添加时间戳
  save_detailed_paths: false       # 保存详细路径信息
  save_logs: true                  # 保存日志文件
  log_level: "INFO"                # 日志级别
  console_output: true             # 控制台输出
  
# 性能监控配置
monitoring:
  enable_real_time_stats: true     # 实时统计
  progress_update_interval: 1000   # 进度更新间隔
  memory_monitoring: false         # 内存监控

# 验证配置
validation:
  verify_path_disjointness: true   # 验证路径不相交性
  check_network_connectivity: true # 检查网络连通性
  validate_traffic_demands: true   # 验证流量需求
